version: '3'

services:
  gpt4-all-web:
    build:
      context: ./docker # Update the build context to the docker directory
      dockerfile: Dockerfile # Remove the "docker/" prefix from the Dockerfile path
    ports:
      - "8028:3000"
    restart: unless-stopped
